Домашнее задание "Основные математические понятия".
Уровень 0:
Представим фильмы в виде бинарных векторов (numpy array) используя следующие признаки:

[Комедия, Боевик, Исторический, Бред Питт, Бенедикт Камбербэтч, Квентин Тарантино]

Игра в имитацию

Ярость

12 лет рабства

Однажды в Голливуде

film_1 = np.array([0,0,0,0,1,0])      # Игра в имитацию

film_2 = np.array([0,1,0,1,0,0])      # Ярость

film_3 = np.array([0,0,1,1,1,0])      # 12 лет рабства

film_4 = np.array([1,0,0,1,0,1])      # Однажды в Голливуде

Задание 1
Найти угол между векторами-фильмами "Ярость" и "12 лет рабства". Результатом будет являться косинусная мера, которую можно использовать для определения похожести векторов.

In [1]:
import numpy as np

In [2]:
film_1 = np.array([0,0,0,0,1,0]) # Игра в имитацию

film_2 = np.array([0,1,0,1,0,0]) # Ярость

film_3 = np.array([0,0,1,1,1,0]) # 12 лет рабства

film_4 = np.array([1,0,0,1,0,1]) # Однажды в Голливуде

In [4]:
np.dot(film_2, film_3) # скалярное произведение векторов

1

In [6]:
np.dot(film_2, film_3)/(np.linalg.norm(film_2)*np.linalg.norm(film_3)) # косинус угла между векторами

0.40824829046386296

In [8]:
np.rad2deg(np.arccos(np.dot(film_2, film_3)/(np.linalg.norm(film_2)*np.linalg.norm(film_3)))) - # угол в градусах

65.90515744788931

Задание 2
Вычислить с помощью Python значение первой производной для функции 8*x*(x+3)**2 в точке 1

In [10]:
import sympy as sym

In [11]:
x=sym.Symbol('x')

In [13]:
f=8*x*(x+3)**2
f

8*x*(x + 3)**2

In [15]:
res=sym.diff(f, x) # производная функции
res

8*x*(2*x + 6) + 8*(x + 3)**2

In [16]:
res.subs(x,1) - # значение производной в точке 1

192

Задание 3
Объединить векторы фильмов в матрицу, где каждый вектор является строкой матрицы. Умножьте вектор [1,2,3,4] на полученную матрицу

In [18]:
m=np.array([film_1,film_2, film_3, film_4])
m

array([[0, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 1, 1, 1, 0],
       [1, 0, 0, 1, 0, 1]])

In [19]:
b= np.array([1,2,3,4])
b

array([1, 2, 3, 4])

In [24]:
b@m # применим матричное умножение

array([4, 2, 3, 9, 4, 4])