Задание 1
Создайте матрицу 3 на 3, заполненную числами от 1 до 9
Прибавьте к ней матрицу с единицами на диагонале
Умножьте полученную матрицу на вектор (1, 2, 3)
Вычислить транспонированную матрицу  от полученной в результате прибавления матрицы
Посчитайте обратную матрицу к полученной в результате прибавления матрице

In [1]:
import numpy as np

In [2]:
A=np.array([[1,2,3], [4,5,6],[7,8,9]])
A # Создайте матрицу 3 на 3, заполненную числами от 1 до 9

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
B = np.eye(3)
B 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
A+B # Прибавьте к ней матрицу с единицами на диагонале

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [6]:
C=np.array([1,2,3])
C

array([1, 2, 3])

In [7]:
(A+B)@C # Умножьте полученную матрицу на вектор (1, 2, 3)

array([15., 34., 53.])

In [8]:
np.transpose(A+B) #Вычислить транспонированную матрицу  от полученной в результате прибавления матрицы

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [9]:
np.linalg.inv(A+B) # Посчитайте обратную матрицу к полученной в результате прибавления матрице

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01,  2.22044605e-17],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

Задание 2
Найдите собственные значения и собственные вектора матрицы:

m = np.array([[2, 2],
              [1, 3]])
print(m)

In [11]:
m = np.array([[2, 2], [1, 3]])
m

array([[2, 2],
       [1, 3]])

In [12]:
np.linalg.eigvals(m) # собственные значени

array([1., 4.])

In [14]:
np.linalg.eig(m)[1]

array([[-0.89442719, -0.70710678],
       [ 0.4472136 , -0.70710678]])

In [16]:
np.linalg.eig(m)[1][0]/0.70710678 #собственные вектора матрицы

array([-1.26491107, -1.        ])

In [19]:
np.linalg.eig(m)[1][1]/0.70710678  #собственные вектора матрицы

array([ 0.63245553, -1.        ])

Задание 3
Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!

In [23]:
A=np.eye(3) #матрица, у которой определитель = 1, и все элементы не равны 0
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.linalg.det(A)

1.0